version: "3.8"
services:
  receipt:
    build: .
    container_name: receipt
    volumes:
      - .:/app
    tty: true # コンテナを起動させ続けるため
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN # Dockerfileで作成したユーザーでchrome起動するためにcapability SYS_ADMINを追加
